config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, only: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :game, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [ :show, :edit, :update, :destroy ]
  def index
    @games = Game.all
  end

  def show

  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
    redirect_to game_path(@game)
  end

  def edit
  end

  def update
    @game.update(game_params)
    redirect_to game_path(@game)
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  protected

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit( :name, :description, :category )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [ :show, :edit, :update, :destroy]
  def new
    @game = Game.find(params[:game_id])
    @review = Review.new
  end

  def create
    @review = Review.new(params_review)
    @review.game = Game.find(params[:game_id])
    @review.save
    redirect_to game_path(params[:game_id])
  end

  def edit
  end

  def update
    @review.update(params_review)
    redirect_to game_path(@review.game_id)
  end

  def destroy
    @game_id = @review.game_id
    @review.delete
    redirect_to game_path(@game_id)
  end

  protected

  def set_review
    @review = Review.find(params[:id])
  end

  def params_review
    params.require(:review).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :category %>
  <%= f.submit "Submit", class: "btn btn-black" %>
  <%= link_to "Back", games_path, class: "btn btn-black" %>
<% end -%>

app/views/games/edit.html.erb
<%= render 'form' %>

app/views/games/index.html.erb
<h1>Games</h1>
<%= link_to "New Game", new_game_path, class: "btn btn-black" %>
<table class="table table-striped">
  <tr id="headers">
    <td><strong>Name</strong></td>
    <td><strong>Category</strong></td>
    <td><strong>Description</strong></td>
    <td></td>
  </tr>
<% @games.each do |game| %>
  <tr>
    <td><%= game.name %></td>
    <td><%= game.category %></td>
    <td><%= game.description %></td>
    <td><%= link_to "More details", game_path(game), class: "btn btn-black btn-sm" %></td>
  </tr>
<% end -%>

app/views/games/new.html.erb
<%= render 'form' %>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<h3>Category: <%= @game.category %></h3>
<h5>Description: <%= @game.description ? @game.description : "not available" %></h5>
<%= link_to "Back", games_path, class: "btn btn-black btn-sm" %>
<%= link_to "Edit", edit_game_path(@game), class: "btn btn-black btn-sm" %>
<%= link_to "Delete game", game_path(@game), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-black btn-sm" %>
<h3>Reviews</h3>
<%= link_to "Add Review", new_game_review_path(@game), class: "btn btn-black" %>

<table class="table table-striped">
  <tr>
    <td><strong>Name</strong></td>
    <td><strong>Review</strong></td>
    <td><strong>Date</strong></td>
    <td></td>
    <td></td>
  </tr>
  <% @game.reviews.each do |review| %>
    <tr>
      <td><%= review.name %></td>
      <td><%= review.content %></td>
      <td><%= review.created_at %></td>
      <td><%= link_to "Edit", edit_review_path, class: "btn btn-black btn-sm" %></td>
      <td><%= link_to "Delete Review", review_path(review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-black btn-sm" %></td>
    </tr>
  <% end -%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsVideoGamesMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for [@game, @review] do |f| %>
  <%= f.input :name %>
  <%= f.input :content %>
  <%= f.submit "Submit", class: "btn btn-black" %>
<% end -%>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= render 'form' %>